### PR TITLE
fix(ml): restore ml.js corrupted by merge #7910

### LINKED ISSUE #8452: bug: ml.js getHeaders() is corrupted with a pasted predictDriverProfit block - API server cannot boot
## Bug: `ml.js` fails to parse — `getHeaders()` is corrupted and the API server cannot boot

**File:** `backend/api/src/services/ml.js` (lines 77–113)

### Summary
The `getHeaders()` helper has been corrupted by a pasted block of code from `predictDriverProfit`. As a result the module contains invalid syntax (`await` used inside a non-async function, plus references to undefined `response` / `method` / `url` / `handleResponse`). Node rejects the module at parse time, so **every file that imports `ml.js` crashes at server boot**.

### Evidence
`node --check backend/api/src/services/ml.js` fails with:

```
SyntaxError: Unexpected reserved word
```

The offending region (lines 83–99) is a copy of the `predictDriverProfit` response-handling block:

```js
if (response.status === 401) {
  throw new Error(`[MLService] Unauthorized (401) for ${method} ${url}`);
}
if (response.status === 403) {
  throw new Error(`[MLService] Forbidden (403) for ${method} ${url}`);
}
const result = await handleResponse(response);
```

`getHeaders()` is a plain (non-async) function; `await` is not legal in it, and `response`, `method`, `url`, and `handleResponse` do not exist in this scope. The function also never `return`s the `headers` object it builds.

### Impact
`ml.js` is imported by at least 5 route files:
- `backend/api/src/routes/driverRoutes.js` (L132)
- `backend/api/src/routes/demandRoutes.js` (L7)
- `backend/api/src/routes/deadheadRoutes.js` (L7)
- `backend/api/src/routes/truckRoutes.js` (L91)
- `backend/api/src/routes/orderRoutes.js` (L173)

Importing any of these fails to parse → the whole API server fails to start. Demand heatmaps, driver profit predictions, deadhead optimization, truck recommendations, and order ML hooks are all unavailable.

### Expected behavior
`getHeaders()` should return an object with `Content-Type: application/json` and, when configured, `X-API-Key`. The stray response-handling block must be removed so the module parses cleanly and the API boots.

### Suggested fix
Delete the pasted `predictDriverProfit` block from `getHeaders()` and `return headers;` at the end of the function.

### PR DESCRIPTION
**Pull request by Akshita-2307**
## Summary

`backend/api/src/services/ml.js` on `main` was corrupted by bad merge PR #7910 (`1db29c84`): the file was resolved to the broken side of the conflict and lost 8 functions that the routes import at startup — `predictDemand`, `predictPrice`, `predictEta`, `matchBilateral`, `predictDriverProfit`, and the internal helpers `handleResponse`, `getBaseUrl`, `_haversineKm`. Because routes import the missing exports (`demandRoutes.js:7`, `driverRoutes.js:132`, `truckRoutes.js:91`, `orderRoutes.js:173`), the API failed to boot (`ReferenceError: ... is not a function`).

This PR rebuilds the file from the last-good commit `01b3cb53` and re-applies the three legitimate post-merge changes from PR #8022 (pickup-deadline fallback, `arrivalTime` = now, empty-recommendations fallback).

## Changes

- Restored the 8 missing functions and the full 15-export surface of `MLService`.
- Re-applied the 3 post-good changes from PR #8022 that were present in HEAD.

## Verification

- `node --check backend/api/src/services/ml.js` passes (exit 0).
- All exports verified present via grep: `predictDemand`, `predictPrice`, `predictEta`, `matchBilateral`, `predictDriverProfit`, etc.
- Diff vs `01b3cb53` is limited to the 3 intended PR #8022 lines.

## Closes

Closes #8452

---

This PR is part of the GSSOC (GirlScript Summer of Code) batch.

## Summary by CodeRabbit

* **New Features**
  * Added machine-learning support for demand forecasting, price prediction, ETA estimation, bilateral matching, and driver-profit prediction.
  * Added intelligent offer matching with fallback recommendations and improved result sorting.
  * Added response caching to improve performance for demand and price predictions.

* **Bug Fixes**
  * Improved validation, timeout handling, API-key protection, and error reporting for ML requests.
  * Ensured en-route matching results consistently include enriched recommendations.

### CODE REVIEW

**Comment by Akshita-2307** [comment]
Closing as a duplicate: the ml.js boot-crash (missing exports from merge #7910) was already fixed and merged on main by PR #8483 (commit f6f4e758, issue #8473). This branch restored the same 15-export surface from the last-good commit and is functionally identical (verified via diff — only difference is guardMlApiKey placement and the MLService default export, which no importer uses). No new change is left to merge.
